Pim\Bundle\CatalogBundle\Model\Product:
    constraints:
        - Pim\Bundle\CatalogBundle\Validator\Constraints\UniqueVariantAxis: ~
        - Pim\Bundle\CatalogBundle\Validator\Constraints\UniqueVariantGroup: ~
    properties:
        values:
            - Symfony\Component\Validator\Constraints\Valid:
                traverse: true
